### ISSUE TITLE
普通登录成功后还是跳转回登录页面

### ISSUE THREAD

**Issue by csyangwen** [phachon/mm-wiki#1]
普通登录验证成功用户和密码后还是跳转回/author/index

**Comment by phachon** [comment]
@csyangwen 超级管理员还是新添加的用户？

**Comment by csyangwen** [comment]
@phachon install 生成的超级管理员

**Comment by phachon** [comment]
@csyangwen 来MM-Wiki QQ群：853467682 详细描述下问题。

**Comment by phachon** [comment]
@csyangwen 是否还存在不能登录问题？
