### ISSUE TITLE
nginx代理(配置项目前缀)

### ISSUE THREAD

**Issue by crazyAJ** [phachon/mm-wiki#111]
如果配置nginx前缀（因为不想配置再根目录），则页面不能找到！！！希望提供统一页面跳转前缀！！！
location /mm-wiki{
			proxy_ignore_client_abort on;
            proxy_set_header  Host       $host;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  REMOTE-HOST $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://127.0.0.1:8000/;
		}

**Comment by bowang** [comment]
请问这个问题有解决方法吗？

**Comment by crazyAJ** [comment]
没有解决，放弃使用
