### ISSUE TITLE
文章和目录排序问题

### ISSUE THREAD

**Issue by njzg** [phachon/mm-wiki#120]
我在document表看到sequence字段，所有值默认为0
前台已经提供了拖动文章的功能
期望：
1、拖动的文章顺序怎么调整，目前完全按照doucument——id排序，是否可以根据sequence排序，即便是手动修改也可以
2、想新增一个目录结构放在最前面，修改sequence  值可以让新增的目录按照该字段排序

**Comment by phachon** [comment]
v0.1.8 add
