### ISSUE TITLE
可以支持按内容搜索吗？

### ISSUE THREAD

**Issue by wwwlxz** [phachon/mm-wiki#124]
发现目前系统只能支持按标题搜索，但很多实际场景需要按内容搜索，是否可以支持

**Comment by opticaloptical** [comment]
按内容搜索功能非常重要，是知识共享的关键功能之一。什么时候能发布呢 @phachon ，谢谢

**Comment by fpmystar** [comment]
这个按照内容搜索非常有必要，请作者尽快添加该功能，谢谢了

**Comment by phachon** [comment]
v0.1.6 已支持
