### ISSUE TITLE
将此项目部署到synology上

### ISSUE THREAD

**Issue by houfan** [phachon/mm-wiki#14]
登录synology的DiskStation, 安装了nginx，mariadb套件，创建虚拟主机的时候，指定家目录的时候我迷糊了.........

这里是 Synology 产品的一套操作系统，DSM。而wiki的版本我打开Sourcecode,发现install目录下有一些go的脚本...需要执行的吧，要go的环境我看

**Comment by phachon** [comment]
@houfan 你在哪下载的安装包?不是 github 吗?
