### ISSUE TITLE
登录超时后正在编辑内容全部丢失

### ISSUE THREAD

**Issue by wongkimshing** [phachon/mm-wiki#18]
在登录超时后正在编辑内容全部丢失，非常影响效率，可否设置为登录以后永不超时或者自动定时保存编辑内容？谢谢

**Comment by phachon** [comment]
@wongkimshing session 和 cookie 过期时间可以修改: conf/mm-wiki
# session 过期时间，单位 s 
sessiongcmaxlifetime= 
# cookie  过期时间，单位  s
cookie_expired= 

session 支持 file,memory,redis 等方式，详见 beego session 配置：
https://beego.me/docs/mvc/controller/session.md

**Comment by swenzi** [comment]
你好，我按照这个配置文件配置了， session还是很容易过期：

配置如下：
![image](https://user-images.githubusercontent.com/3942676/45737851-7bb1e980-bc21-11e8-9112-404542a9537c.png)

**Comment by phachon** [comment]
@swenzi 配置完重启了么

**Comment by swenzi** [comment]
> @swenzi 配置完重启了么

重启了，会不会是使用了nginx反向代理的原因呢？
