### ISSUE TITLE
mmwiki 保存文件后宕机

### ISSUE THREAD

**Issue by blogshixiaodong** [phachon/mm-wiki#181]
问题：保存了约200KB+ 的markdown文档后点击保存，然后随机点几篇文章，直接无法访问，其次在编辑的时候也异常的卡顿。后续重启也出现无法启动的情况，通过top看到CPU 200%+， Mem 90%+;
处理方式：只是暂时的处理方式，将数据库中对应的表的记录删掉，再删除./mmwiki/files/search-index下的文件（索引？）就能重启。

1. 当前使用的版本号
Version: v0.1.9

2. 是否已经升级到新版本
是

**Comment by blogshixiaodong** [comment]
logs下异常信息：
2020/04/26 22:33:09.709 [I] [asm_amd64.s:1337]  http server Running on http://0.0.0.0:8080
2020/04/26 22:33:29.126 [D] [controller.go:306]  template Execute err: template: main/default.html:28:45: executing "main/default.html" at <eq $logDocument.document_type "1">: error calling eq: invalid type for comparison

**Comment by buray** [comment]
文章内容过大，保存之后会造成宕机，mmwiki启动后，mmwiki会启动10个进程，同时会有大量的mysql链接产生，当时内存增加不是很明显，随着：
2020/05/05 09:40:44.298 [I] [doc_search.go:25]  [loadSearchIndex] start load doc index
2020/05/05 09:40:44.299 [I] [doc_search.go:25]  [loadSearchIndex] get all doc finish
2020/05/05 09:40:44.326 [I] [doc_search.go:25]  [loadSearchIndex] add index finish
2020/05/05 09:40:44.425 [I] [doc_search.go:25]  [loadSearchIndex] index flush finish
循环，内存会逐步增加，如果有多篇大文本，表现会很明显，超出内存之后直接被内核杀死。
/var/log/messages:May  5 09:04:10 VM_0_7_centos kernel: Killed process 11600 (mm-wiki), UID 0, total-vm:1875612kB, anon-rss:1531988kB, file-rss:0kB, shmem-rss:0kB
/var/log/messages:May  5 09:14:32 VM_0_7_centos kernel: Killed process 12923 (mm-wiki), UID 0, total-vm:1968184kB, anon-rss:1529184kB, file-rss:0kB, shmem-rss:0kB
/var/log/messages:May  5 09:36:08 VM_0_7_centos kernel: Killed process 16098 (mm-wiki), UID 0, total-vm:1801252kB, anon-rss:1523448kB, file-rss:0kB, shmem-rss:0kB
/var/log/messages:May  5 09:50:19 VM_0_7_centos kernel: Killed process 17909 (mm-wiki), UID 0, total-vm:1901480kB, anon-rss:1472928kB, file-rss:0kB, shmem-rss:0kB

**Comment by laoflch** [comment]
我们这里也碰见相同情况，内存和cpu的使用很高，根本无法使用

**Comment by muzyer** [comment]
各位找到临时方案了吗？目前系统关闭中，用不了；

**Comment by phachon** [comment]
v0.2.1
