### ISSUE TITLE
v0.1.3升级到v0.1.9后启动失败

### ISSUE THREAD

**Issue by xdxiaodao** [phachon/mm-wiki#188]
v0.1.3升级到v0.1.9后启动失败

1. 当前使用的版本号
v0.1.3

2. 是否已经升级到新版本
是v0.1.9

3. 当前遇到的问题
升级后启动报错

4. 错误日志或截图
![error](https://user-images.githubusercontent.com/10125255/81550717-38d2f580-93b3-11ea-85c4-aa34c6adccbc.jpg)
错误日志详细内容：
[mm_wiki_error.txt](https://github.com/phachon/mm-wiki/files/4608952/mm_wiki_error.txt)

5. 希望增加的功能
无，解决升级报错问题

**Comment by xdxiaodao** [comment]
网上查了下，应该是riot组件使用内存比较高造成的，验证了下，使用8核16G内存机器跑，确实不再报错，但是进程会被oom掉

**Comment by xdxiaodao** [comment]
确认了下，应该是初始化分词器导致内存占用过高之后被系统kill掉了：
2020/05/12 10:07:11 Dict files path:  [docs/search_dict/dictionary.txt]
2020/05/12 10:07:11 Load the gse dictionary: "docs/search_dict/dictionary.txt" 
2020/05/12 10:07:11 Gse dictionary loaded finished.
2020/05/12 10:07:31.031 [I] [doc_search.go:14]  [loadSearchIndex] start load doc index
2020/05/12 10:07:31.035 [I] [doc_search.go:14]  [loadSearchIndex] get all doc finish
Killed

**Comment by phachon** [comment]
@xdxiaodao 文件大概有多少

**Comment by ourforPP** [comment]
也是同样的问题，不过我是在刷新分词的时候炸掉，目前只能把刷新时间加的无限大来保持稳定运行

**Comment by iDorr** [comment]
同样的问题，怎么解决啊

**Comment by phachon** [comment]
v0.2.1 去掉这个搜索了，后面再重新计划
