### ISSUE TITLE
发邮件有点问题

### ISSUE THREAD

**Issue by iamif3000** [phachon/mm-wiki#19]
我配置了邮件服务器和用户信息，也启用了“开启邮件通知”。用户1也关注了文档1，但是用户2修改文档1的时候，用户1没有收到邮件。而且mysql和文件日志上也没有出错的日志。

**Comment by phachon** [comment]
@iamif3000 用的是什么邮件服务器？如果使用的是 qq 邮箱的话。密码需要使用授权码。

**Comment by iamif3000** [comment]
阿里云的企业邮箱。所有的设置都设了的，然后也启用了邮件通知。

**Comment by wongkimshing** [comment]
我也遇到同样问题

**Comment by iamif3000** [comment]
@wongkimshing ，你解决了么？

**Comment by phachon** [comment]
已修复
