### ISSUE TITLE
最新版本(V0.1.9)分词搜索再文档量较大的情况下失败

### ISSUE THREAD

**Issue by shenxiaomei** [phachon/mm-wiki#190]
文档量较大的时候，启动失败

1. 当前使用的版本号
v0.1.9

2. 是否已经升级到新版本
是

3. 当前遇到的问题
现有文档量：8044， 现版本：v0.1.3，成功升级到最新后，重启启动，提示content err: Too many connections

4. 错误日志或截图
xxx
![image](https://user-images.githubusercontent.com/49012022/82187272-bd2af880-991e-11ea-848f-8ca021263570.png)

5. 希望增加的功能
解决此问题，支持较大文档量的搜索。

**Comment by shenxiaomei** [comment]
![image](https://user-images.githubusercontent.com/49012022/82402780-dacb9f80-9a8f-11ea-8649-3de9d36997d3.png)
服务器内存是够的

**Comment by phachon** [comment]
v0.2.1
