### ISSUE TITLE
迁移mm-wiki到其他服务器后，访问一会儿页面，容器自动 Exited

### ISSUE THREAD

**Issue by 815325223** [phachon/mm-wiki#197]
迁移mm-wiki到其他服务器后，访问一会儿页面，容器自动 Exited
1. 当前使用的版本号
v0.1.9

2. 是否已经升级到新版本
最新版本

3. 当前遇到的问题
mysql 数据库主主模式，wiki 通过 VIP 连接，wiki 数据拷贝到另外一台服务器，容器启动后，页面访问一会儿，容器就自动退出了。

4. 错误日志或截图
2020/05/30 23:44:18.034 [I] [asm_amd64.s:1373]  http server Running on http://0.0.0.0:8081
2020/05/30 23:44:19.609 [C] [panic.go:967]  the request url is  /author/logout
2020/05/30 23:44:19.609 [C] [panic.go:967]  Handler crashed with error interface conversion: interface {} is nil, not map[string]string
2020/05/30 23:44:19.609 [C] [panic.go:967]  /usr/local/go/src/runtime/panic.go:967
2020/05/30 23:44:19.609 [C] [panic.go:967]  /usr/local/go/src/runtime/iface.go:260
2020/05/30 23:44:19.609 [C] [panic.go:967]  /app/mm-wiki/app/controllers/template.go:318
2020/05/30 23:44:19.610 [C] [panic.go:967]  /app/mm-wiki/app/controllers/template.go:346
2020/05/30 23:44:19.610 [C] [panic.go:967]  /app/mm-wiki/app/controllers/author.go:202
2020/05/30 23:44:19.610 [C] [panic.go:967]  /usr/local/go/src/reflect/value.go:460
2020/05/30 23:44:19.610 [C] [panic.go:967]  /usr/local/go/src/reflect/value.go:321
2020/05/30 23:44:19.610 [C] [panic.go:967]  /go/pkg/mod/github.com/astaxie/beego@v1.12.0/router.go:853
2020/05/30 23:44:19.610 [C] [panic.go:967]  /usr/local/go/src/net/http/server.go:2807
2020/05/30 23:44:19.610 [C] [panic.go:967]  /usr/local/go/src/net/http/server.go:1895
2020/05/30 23:44:19.610 [C] [panic.go:967]  /usr/local/go/src/runtime/asm_amd64.s:1373
2020/05/30 23:44:47.785 [I] [doc_search.go:25]  [loadSearchIndex] start load doc index
2020/05/30 23:44:47.792 [I] [doc_search.go:25]  [loadSearchIndex] get all doc finish
2020/05/30 23:44:48.128 [I] [doc_search.go:25]  [loadSearchIndex] add index finish
2020/05/30 23:44:48.538 [I] [doc_search.go:25]  [loadSearchIndex] index flush finish
2020/05/30 23:45:18.540 [I] [doc_search.go:25]  [loadSearchIndex] start load doc index
2020/05/30 23:45:18.549 [I] [doc_search.go:25]  [loadSearchIndex] get all doc finish
2020/05/30 23:45:19.060 [I] [doc_search.go:25]  [loadSearchIndex] add index finish
2020/05/30 23:45:19.594 [I] [doc_search.go:25]  [loadSearchIndex] index flush finish
2020/05/30 23:45:49.622 [I] [doc_search.go:25]  [loadSearchIndex] start load doc index
2020/05/30 23:45:49.766 [I] [doc_search.go:25]  [loadSearchIndex] get all doc finish
2020/05/30 23:51:39.063 [I] [doc_search.go:14]  [loadSearchIndex] start load doc index
2020/05/30 23:51:39.065 [I] [doc_search.go:14]  [loadSearchIndex] get all doc finish
2020/05/30 23:51:39.462 [I] [doc_search.go:14]  [loadSearchIndex] add index finish
2020/05/30 23:51:40.145 [I] [doc_search.go:14]  [loadSearchIndex] index flush finish
2020/05/30 23:51:40.424 [I] [asm_amd64.s:1373]  http server Running on http://0.0.0.0:8081
2020/05/30 23:52:10.149 [I] [doc_search.go:25]  [loadSearchIndex] start load doc index
2020/05/30 23:52:10.157 [I] [doc_search.go:25]  [loadSearchIndex] get all doc finish
2020/05/30 23:52:10.257 [I] [doc_search.go:25]  [loadSearchIndex] add index finish
2020/05/30 23:52:10.712 [I] [doc_search.go:25]  [loadSearchIndex] index flush finish
2020/05/30 23:52:40.714 [I] [doc_search.go:25]  [loadSearchIndex] start load doc index
2020/05/30 23:52:40.718 [I] [doc_search.go:25]  [loadSearchIndex] get all doc finish
2020/05/30 23:52:40.897 [I] [doc_search.go:25]  [loadSearchIndex] add index finish
2020/05/30 23:52:41.920 [I] [doc_search.go:25]  [loadSearchIndex] index flush finish
2020/05/30 23:53:11.934 [I] [doc_search.go:25]  [loadSearchIndex] start load doc index
2020/05/30 23:53:11.939 [I] [doc_search.go:25]  [loadSearchIndex] get all doc finish

5. 希望增加的功能
N/A

**Comment by 815325223** [comment]
补充下容器内的输出：
goroutine 572 [chan send]:
github.com/go-ego/riot.(*Engine).internalIndexDoc(0x1655740, 0xc0019e018a, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/go-ego/riot@v0.0.0-20191215221243-bdbc256e4cbd/engine.go:414 +0x1da
github.com/go-ego/riot.(*Engine).Index(0x1655740, 0xc0019e018a, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/go-ego/riot@v0.0.0-20191215221243-bdbc256e4cbd/engine.go:389 +0x9a
github.com/go-ego/riot.(*Engine).IndexDoc(...)
	/go/pkg/mod/github.com/go-ego/riot@v0.0.0-20191215221243-bdbc256e4cbd/engine.go:372
github.com/phachon/mm-wiki/app/work.loadDocSearchIndex.func1(0xc0019e14c0, 0xc0073bb170)
	/app/mm-wiki/app/work/doc_search.go:63 +0x2c7
created by github.com/phachon/mm-wiki/app/work.loadDocSearchIndex
	/app/mm-wiki/app/work/doc_search.go:46 +0x13b

goroutine 395 [IO wait]:
internal/poll.runtime_pollWait(0x7fd60ab78930, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0153af518, 0x72, 0x0, 0x0, 0xd77dc0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0153af500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc0153af500, 0xa1ef96787a752b1e, 0x0, 0xa1ef96787a752b1e)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0070b0020, 0x5ed28167, 0xc0015e6dc0, 0x4d2686)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0070b0020, 0xc0015e6e10, 0x18, 0xc0288bcf00, 0x711a5c)
	/usr/local/go/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0xc0001581c0, 0xee0360, 0xc0070b0020, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2901 +0x25d
net/http.(*Server).ListenAndServe(0xc0001581c0, 0xeb9390, 0xc028d087a0)
	/usr/local/go/src/net/http/server.go:2830 +0xb7
github.com/astaxie/beego.(*App).Run.func4(0xc01c65c090, 0xc, 0xc00015e290, 0xc029b7b180)
	/go/pkg/mod/github.com/astaxie/beego@v1.12.0/app.go:231 +0x263
created by github.com/astaxie/beego.(*App).Run
	/go/pkg/mod/github.com/astaxie/beego@v1.12.0/app.go:213 +0x2ab

goroutine 461 [select, 1 minutes]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc01cc251a0, 0xc028d226c0, 0xc01ca2ca20)
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.4.1/connection_go18.go:178 +0xbf
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.4.1/connection_go18.go:175 +0xbe

**Comment by phachon** [comment]
v0.2.1
