### ISSUE TITLE
function "dateFormat" not defined

### ISSUE THREAD

**Issue by wlpeter** [phachon/mm-wiki#20]
我运行系统时，总是报错，如下：
`2018/09/03 17:08:32.359 [E] [template.go:174] parse template err: system/profile/activity.html template: system/profile/activity.html:51: function "dateFormat" not defined
panic: template: system/profile/activity.html:51: function "dateFormat" not defined

goroutine 1 [running]:
mm-wiki/vendor/github.com/astaxie/beego.initBeforeHTTPRun()
	/root/workspace/goworkspace/src/mm-wiki/vendor/github.com/astaxie/beego/beego.go:98 +0x111
mm-wiki/vendor/github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/root/workspace/goworkspace/src/mm-wiki/vendor/github.com/astaxie/beego/beego.go:55 +0x26
main.main()
	/root/workspace/goworkspace/src/mm-wiki/main.go:9 +0x3c
exit status 2
`

**Comment by wlpeter** [comment]
用的是最新的版本，源码没进行修改

**Comment by wlpeter** [comment]
@phachon 我找到问题了，是我这边的问题，不好意思

**Comment by Liu-HongYe** [comment]
@wlpeter 我也遇到了相同的问题, 请问您是怎么解决的?
