### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by mayuncun** [phachon/mm-wiki#209]
1. 当前使用的版本号
v0.1.9

2. 是否已经升级到新版本
是

3. 当前遇到的问题
内存占用过高，会把系统内存都吃掉，造成访问卡顿，而且长时间不访问也不会减少，怀疑有内存泄漏。

4. 错误日志或截图
![捕获](https://user-images.githubusercontent.com/8216288/84846377-397d3c80-b081-11ea-8503-f56cb07a0a58.PNG)

5. 希望增加的功能

**Comment by phachon** [comment]
v0.2.1 done.
