### ISSUE TITLE
v0.19 内存不释放

### ISSUE THREAD

**Issue by caihuazhg** [phachon/mm-wiki#217]
发现v0.1.9版本分配对少内存给OS都会被mm-wiki使用完 

1. 当前使用的版本号
v0.1.9

2. 是否已经升级到新版本
最新release

3. 当前遇到的问题
mm-wiki耗尽内存

4. 错误日志或截图
![image](https://user-images.githubusercontent.com/10457741/87243103-bb386e00-c465-11ea-8063-487d3a1a146a.png)

5. 希望增加的功能
页面部分 分两列 左侧显示内容 右边显示目录

**Comment by kuangdongwei** [comment]
我也碰到了oom问题，然后直接挂掉了。。。。
如何解决？？？

**Comment by caihuazhg** [comment]
不知道 也没有回应

**Comment by phachon** [comment]
更新最新版 v0.2.1
