### ISSUE TITLE
内存积累很多

### ISSUE THREAD

**Issue by zdYng** [phachon/mm-wiki#219]
xxxxx这里是问题描述xxxx

1. 当前使用的版本号
v0.1.9

2. 是否已经升级到新版本
是
3. 当前遇到的问题
内存占用越来越多

4. 错误日志或截图
![image](https://user-images.githubusercontent.com/17880611/87440316-698a1200-c624-11ea-96d9-6f15e8a2d023.png)

5. 希望增加的功能
内存占用小点

**Comment by zdYng** [comment]
![image](https://user-images.githubusercontent.com/17880611/87440813-f92fc080-c624-11ea-8398-35b526ab68bf.png)
 会一直重启

**Comment by zdYng** [comment]
v0.2版本什么时候更新上线呀

**Comment by zdYng** [comment]
应该已经修复了吧

**Comment by zdYng** [comment]
v0.1.9的bug吧

**Comment by phachon** [comment]
v0.2.1
