### ISSUE TITLE
windows运行自动挂掉

### ISSUE THREAD

**Issue by kuangdongwei** [phachon/mm-wiki#220]
xxxxx这里是问题描述xxxx

1. 当前使用的版本号
v0.1.9

2. 是否已经升级到新版本
是

3. 当前遇到的问题
自动挂掉，重启不到一分钟同样原因又会挂掉
runtime: out of memory: can not allocaate......
fatal error: out of memory...
.......

4. 错误日志或截图
<img width="605" alt="批注 2020-07-18 143809" src="https://user-images.githubusercontent.com/41977700/87846745-bb70b780-c904-11ea-8a3c-834d4dd7ebcb.png">

5. 希望增加的功能
xxx

**Comment by Fly-Bird** [comment]
同样的问题，我这里Windows，Centos都部署了，如果不加任何数据可以稳定运行

**Comment by phachon** [comment]
v0.2.1
