### ISSUE TITLE
docker运行会被kill

### ISSUE THREAD

**Issue by zdYng** [phachon/mm-wiki#223]
xxxxx这里是问题描述xxxx

1. 当前使用的版本号
v0.1.9

2. 是否已经升级到新版本
yes

3. 当前遇到的问题
./mm-wiki --conf conf/mm-wiki.conf

4. 错误日志或截图
docker运行会被kill
![image](https://user-images.githubusercontent.com/17880611/88142667-77ddbc80-cc28-11ea-968a-099a86767825.png)

5. 希望增加的功能
xxx

**Comment by phachon** [comment]
v0.2.1
