### ISSUE TITLE
运行几分钟会自动killed

### ISSUE THREAD

**Issue by zdYng** [phachon/mm-wiki#224]
xxxxx这里是问题描述xxxx

1. 当前使用的版本号
v0.1.9

2. 是否已经升级到新版本
是

3. 当前遇到的问题
程序自动被killed，占用内存飙升

4. 错误日志或截图
xxx
![image](https://user-images.githubusercontent.com/17880611/88494241-bb994300-cfe7-11ea-8aab-738f04e6aaee.png)

![image](https://user-images.githubusercontent.com/17880611/88494250-cfdd4000-cfe7-11ea-849f-16898576a24f.png)

5. 希望增加的功能
xxx

**Comment by zhuminjie1018** [comment]
一开始数据不多，倒是蛮稳定的。我部署在阿里云上运行了约3个月，最近占用资源过多，一启动进程过5分钟左右，系统就及其卡，就会被阿里云自动kill掉。

**Comment by phachon** [comment]
v0.2.1
