### ISSUE TITLE
内存泄露问题

### ISSUE THREAD

**Issue by qumoy** [phachon/mm-wiki#228]
xxxxx这里是问题描述xxxx

1. 当前使用的版本号
v0.1.9

2. 是否已经升级到新版本
是

3. 当前遇到的问题
内存泄露
回退到0.1.6，0.1.8版本也会出现同样的问题。
有没有什么能正确回退版本的方法？不影响正常的使用，大佬求教！！！

**Comment by phachon** [comment]
更新最新版本 v0.2.1
