### ISSUE TITLE
内存泄漏严重

### ISSUE THREAD

**Issue by haoyuanliu** [phachon/mm-wiki#229]
xxxxx这里是问题描述xxxx

1. 当前使用的版本号
v0.1.9

2. 是否已经升级到新版本
是

3. 当前遇到的问题
内存泄漏自动宕机

4. 错误日志或截图
xxx

5. 希望增加的功能
希望大佬尽快解决内存泄漏的问题！

**Comment by phachon** [comment]
更新最新版本v0.2.1
