### ISSUE TITLE
用户不应该看到没权限的空间列表

### ISSUE THREAD

**Issue by wongkimshing** [phachon/mm-wiki#23]
用户不应该看到没权限的空间列表，如果一个用户只能编辑或查看A空间，那他应该只有A空间在他的空间列表里，不应该看到其他的，您觉得对吗？

**Comment by wongkimshing** [comment]
本来我打算这个可以作为知识库共享给客户，但因为这个原因没办法，不能让客户看到列表里的其他客户名称，这个产品很好，但可否改进一下？谢谢

**Comment by soease** [comment]
是否添加一个查看权限之类的控制，让权限控制共享功能
