### ISSUE TITLE
LDAP无法配置

### ISSUE THREAD

**Issue by leciel0701** [phachon/mm-wiki#239]
1. 当前使用的版本号
v0.2.0

2. 当前遇到的问题
LDAP统一认证

LDAP统一认证无法登陆,示例不是很明确
我的DN是 识别名（DN）: cn=xxxxx,cn=xxx,ou=xxxxxx,dc=example,dc=com
在示例中完全不知道怎么对应字段
只添加 {"basedn":"dc=example,dc=com","bind_username":"Manager","bind_password":"88888888"}可以认证通过但是无法登陆
添加任一其他字段,认证就无法通过

示例可以更详细一些么?或者有可能的话,可以加个UI来填写各字段么

**Comment by leciel0701** [comment]
Leave

**Comment by fanddong** [comment]
bind_username，这个字段需要写全，不写全的话后台报dn无效
