### ISSUE TITLE
内存占用过大，无法启动

### ISSUE THREAD

**Issue by isking2008** [phachon/mm-wiki#244]
xxxxx内存占用过大，无法启动xxxx

1. 当前使用的版本号
v0.2.0

2. 是否已经升级到新版本
是

3. 当前遇到的问题
执行 `./mm-wiki --conf conf/mm-wiki.conf` 启动后内存立即飙升，过一会进程挂掉，无法启动

4. 错误日志或截图

5. 希望增加的功能
正常启动，

**Comment by phachon** [comment]
更新最新版 v0.2.1
