### ISSUE TITLE
LDAP认证的附加参数（配置数据）长度超过限制

### ISSUE THREAD

**Issue by mikya-fff** [phachon/mm-wiki#245]
1. 当前使用的版本号
v0.2.0

2. 是否已经升级到新版本
全新安装，不是升级

3. 当前遇到的问题
添加ldap登录认证方式时，附加参数太长，导致认证失败

4. 错误日志或截图
```
添加登录认证失败：Error 1406: Data too long for column 'ext_data' at row 1
```

解决办法：

修改`mw_login_auth`表中的`ext_data`字段为varchar(n),n是指字符长度。如果ldap的目录结构复杂一些，100个字符根本不够用

**Comment by phachon** [comment]
@mikya-fff 新版已更新数据库字段类型，需手动修改下
