### ISSUE TITLE
统一登录出错

### ISSUE THREAD

**Issue by brucezrh** [phachon/mm-wiki#264]
xxxxx这里是问题描述xxxx

1. 当前使用的版本号
 v0.2.1

2. 是否已经升级到新版本
是
3. 当前遇到的问题
配置了登录认证，但是登录报错

4. 错误日志或截图
2020/11/17 13:51:33.092 [E] [value.go:447]  统一登录失败： 绑定 LDAP 用户失败, err=LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903D9, comment: AcceptSecurityContext error, data 52e, v2580
配置情况
 用户名前缀：ldap
认证URL：ldap://IP:389
附加参数：
{
"basedn":"dc=buycoor,dc=com",
"bind_username":"bruce.zhang",
"bind_password":"123456"
}

**Comment by brucezrh** [comment]
已处理

**Comment by g00n1** [comment]
我也碰到这个问题，有解决吗？0.2.1 版本 by 2020-12-24

**Comment by jason-zxsies** [comment]
怎么处理的，不说下呀？
