### ISSUE TITLE
上传超过1024k附件时，提示上传失败

### ISSUE THREAD

**Issue by superrrrrrrrL** [phachon/mm-wiki#266]
![337909E8-02C5-4ce5-B1AC-F3207B28B0EF](https://user-images.githubusercontent.com/32129586/99475758-2b15b280-298a-11eb-9bd1-aa83f95d545a.png)
![CB8865C0-12FA-423c-ABCE-FC6BA90F7232](https://user-images.githubusercontent.com/32129586/99475771-32d55700-298a-11eb-8558-04ce025fe0bb.png)
![FA326C34-A45B-42ec-8C76-D58E654D0536](https://user-images.githubusercontent.com/32129586/99475774-349f1a80-298a-11eb-944d-db44a251394c.png)

**Comment by JayLeeZed** [comment]
![A900C5C0-1152-4462-970B-F686B1B1A3A2](https://user-images.githubusercontent.com/32129586/99475989-a8d9be00-298a-11eb-926e-95a136e56443.png)
![1BC1C8E8-1D10-48f9-A46E-37673E41A9F3](https://user-images.githubusercontent.com/32129586/99475990-a9725480-298a-11eb-95b5-e3b719a5b457.png)

**Comment by JayLeeZed** [comment]
![Uploading DA40951A-D4C4-4c9d-8D7A-B65B005A51C2.png…]()

**Comment by JayLeeZed** [comment]
![DA40951A-D4C4-4c9d-8D7A-B65B005A51C2](https://user-images.githubusercontent.com/32129586/99476242-23a2d900-298b-11eb-803f-fcdbbfb00f5b.png)

**Comment by superrrrrrrrL** [comment]
找到原因了,nigix默认上传最大1m,修改nginx配置后解决
