### ISSUE TITLE
空间添加成员超过15条，提示人员已存在

### ISSUE THREAD

**Issue by BoBoMoon** [phachon/mm-wiki#295]
xxxxx这里是问题描述xxxx

1. 当前使用的版本号
v0.2.1

2. 是否已经升级到新版本
是

3. 当前遇到的问题
给空间添加成员的时候，人数超过15个，没有过滤到。导致已经添加的人，在第二页，结果添加列表里还有这个人，点击添加报人员已存在。除非将单页显示人数设置高，才会过滤掉。

4. 错误日志或截图

5. 希望增加的功能

**Comment by JackyTianer** [comment]
#296

**Comment by BoBoMoon** [comment]
已修复
