### ISSUE TITLE
是否可以支持图片粘贴而非上传-已经自己实现并且pr了，等待作者大大通过

### ISSUE THREAD

**Issue by vCassius** [phachon/mm-wiki#309]
是否可以支持图片粘贴而非上传

1. 当前使用的版本号
MM-Wiki: v0.2.1

2. 是否已经升级到新版本
是

3. 希望增加的功能
希望可以粘贴图片完成上传

**Comment by lkyw5210** [comment]
想问+1

**Comment by Cassuis** [comment]
> 想问+1

我自己写了这个功能。我pr一下

**Comment by bravelee** [comment]
迫切需要这个功能 +1

**Comment by bravelee** [comment]
同时还希望增加页面编辑模式下，Ctrl + S 可以保存文档，现在每次都要点击「 保存」按钮才能保存文档，保存之后想要编辑还需点击「 编辑」按钮，太过麻烦，谢谢

**Comment by Zther0** [comment]
合入了嘛？

**Comment by GX158** [comment]
您的邮件已收到，谢谢！

**Comment by vCassius** [comment]
> 合入了嘛？

合了的
