### ISSUE TITLE
空间创建时的设置不起效

### ISSUE THREAD

**Issue by Thunder-CL** [phachon/mm-wiki#338]
创建空间时设置了不分享，在创建空间后，页面自动重新加载，显示刚刚创建的空间是可分享的

1. 当前使用的版本号
v0.2.1

2. 是否已经升级到新版本
是

3. 当前遇到的问题
创建空间时设置了不分享，在创建空间后，页面自动重新加载，显示刚刚创建的空间是可分享的

4. 错误日志或截图
暂无报错，功能缺陷

5. 希望增加的功能
无

**Comment by phachon** [comment]
fix v0.2.2
