### ISSUE TITLE
登录功能有Bug

### ISSUE THREAD

**Issue by Thunder-CL** [phachon/mm-wiki#339]
登录功能Bug

当前使用的版本号
v0.2.1

是否已经升级到新版本
是

当前遇到的问题
例如系统已存在可正常登录的用户名称为Chang，如果使用chang作为用户名登录，系统提示登录成功，但是仍然会返回到登录界面，实际上是没有登录成功的。

错误日志或截图
暂无报错，功能缺陷

希望增加的功能
无

**Comment by phachon** [comment]
最新版本已修复

**Comment by qq253498229** [comment]
> 最新版本已修复

请问哪个版本修复的啊，还是这样啊
