### ISSUE TITLE
部署建议

### ISSUE THREAD

**Issue by xtay573269555** [phachon/mm-wiki#35]
go写的程序就是好，不用装一堆乱七八糟的一堆。刚安装了下，提点建议，仅供参考。

1.可使用普通用户用80端口运行该程序
# setcap cap_net_bind_service=+eip /home/zfr/mm/mm-wiki

2.WEB界面首次安装时，建议将“开始自动安装”改成“运行安装向导”。“开始自动安装”给人的感觉是虽然我要安装wiki，但程序到底要装哪些或配置哪些我都不知道，它就要运行一堆东西了。

3.数据库配置那里，标明一下支持哪些（或哪些测试过）的数据库名称吧

**Comment by phachon** [comment]
@xtay573269555 下一版本将采纳， 感谢支持并提出建议
