### ISSUE TITLE
统一登录--提示登录成功后又跳转登录界面

### ISSUE THREAD

**Issue by wolcengit** [phachon/mm-wiki#364]
统一登录--提示登录成功后又跳转登录界面

1. 当前使用的版本号
master编译运行

2. 是否已经升级到新版本
xxx

3. 当前遇到的问题
xxx

4. 错误日志或截图
xxx

5. 希望增加的功能
xxx

**Comment by GX158** [comment]
您的邮件已收到，谢谢！

**Comment by wolcengit** [comment]
LDAP登录账户使用userPrincipalName可以登录，但无法进入系统，修改为sAMAccountName则可以正常使用
