### ISSUE TITLE
手动删除mw_document表中数据后 首页报错

### ISSUE THREAD

**Issue by BorisWJ** [phachon/mm-wiki#37]
RT 在删除数据库mw_document表中某几条数据后,刷新主页显示如下报错 页面没有任何输出 请问问题出在哪?怎么解决?
2018/11/27 10:47:10.821 [D] [controller.go:263] template Execute err: template: main/default.html:21:45: executing "main/default.html" at <eq $logDocument.docu...>: error calling eq: invalid type for comparison

**Comment by phachon** [comment]
@BorisWJ 不要乱删数据

**Comment by BorisWJ** [comment]
> @BorisWJ 不要乱删数据

首页最近更新文档里都是假数据 文章都已经删除了 最近更新里还显示 不去库里删脏数据 那在哪删?
