### ISSUE TITLE
安装失败，提示创建数据库出错

### ISSUE THREAD

**Issue by ming42** [phachon/mm-wiki#45]
错误提示：
创建数据库出错：Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-wiki CHARACTER SET utf8' at line 1

Server:			MariaDB
Server version:		10.1.37-MariaDB-0+deb9u1 Debian 9.6
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	utf8mb4
Db     characterset:	utf8mb4
Client characterset:	utf8mb4
Conn.  characterset:	utf8mb4

另外，内存限值最低500M有什么依据吗？在一个492M的KVM上尝试安装失败，只能手动修改了下install.go

**Comment by phachon** [comment]
v0.1.3 fix

**Comment by SpiritLing** [comment]
我的也出同样问题，好像是数据库版本问题，mm-wiki 数据库名字格式不支持，可以使用mm_wiki名字，我的是这样问题，不知道对你有没有帮助
