### ISSUE TITLE
建议增加全文搜索

### ISSUE THREAD

**Issue by jackliuhq** [phachon/mm-wiki#59]
请问能不能增加：页面的关键字功能，以及全文索引检索功能？

**Comment by phachon** [comment]
@jackliuhq 正在规划中

**Comment by zuiyuewentian** [comment]
希望尽快添加全文索引，正在给公司内部推广

**Comment by qiaoyinlu** [comment]
觉得唯一的遗憾就是没有全文检索~很棒的产品。

**Comment by cxgreat2014** [comment]
希望尽快添加全文索引功能，同样期待给公司内部推广

**Comment by phachon** [comment]
v0.1.6 已支持全文搜索

**Comment by AwadYoo** [comment]
v0.2.1 还是只支持标题搜索呀

**Comment by zyt2138** [comment]
v2.0是支持的，但是全文检索有bug，太吃内存，v0.2.1给关掉了
