### ISSUE TITLE
后期是否有精力是否能增加 ONLYOFFICE  功能 

### ISSUE THREAD

**Issue by smirkcat** [phachon/mm-wiki#7]
RT 

ONLYOFFICE

https://github.com/ONLYOFFICE/Docker-DocumentServer

https://github.com/3xxx/ONLYOFFICE-golang  别人已有的项目 

这样就可以支持 DOC, DOCX, TXT, ODT, RTF, ODP, EPUB, ODS, XLS, XLSX, CSV, PPTX, HTML

**Comment by phachon** [comment]
@smirkcat 这是个很好的项目，更像是一个云端的文档管理软件，MM-Wiki的定位并不是对各种文档（TXT, DOC,XLS）的管理，而是提供一个多人协作的写作系统来提高团队效率。当然，我觉得 ONLYOFFICE 功能可以加入后期的文档附件预览上。
