### ISSUE TITLE
无法打开安装页面

### ISSUE THREAD

**Issue by sosyz** [phachon/mm-wiki#70]
系统环境CentOS 7
网络环境 家庭局域网（192.168.x.x）
在ssh上curl是可以访问的，本地用浏览器就是长时间未响应
使用宝塔，已放行8090

**Comment by phachon** [comment]
@sosyz 应该是 linux 防火墙的问题，端口没开

**Comment by sosyz** [comment]
> @sosyz 应该是 linux 防火墙的问题，端口没开
把防火墙禁用以后访问还是这个情况

**Comment by sosyz** [comment]
> @sosyz 应该是 linux 防火墙的问题，端口没开
使用systemctl stop firewalld.service 暂时关闭防火墙 可以访问了，非常感谢
