### ISSUE TITLE
贡献点代码，剪切板图片直接复制进编辑框的

### ISSUE THREAD

**Issue by ourfor-pp** [phachon/mm-wiki#71]
没有几行代码，就借问题贡献好了。
没多少时间，随便写的，希望作者再优化下吧

效果：可以直接将截图保存到剪切板的图片插入到文档里

/static/plugin/editor.md/editormd.js  加到722行
```
            //监听剪切板事件
            var cm = this.cm;
            this.codeMirror[0].addEventListener("paste", function (e) {
                if ( !(e.clipboardData && e.clipboardData.items) ) {
                    return;
                }
                var items = (event.clipboardData && event.clipboardData.items) || [];
                var file = null;
                if (items && items.length) {
                    for (var i = 0; i < items.length; i++) {
                        if (items[i].type.indexOf('image') !== -1) {
                            file = items[i].getAsFile();
                            break;
                        }
                    }
                }
                var reader = new FileReader();
                reader.readAsDataURL(file);
                var formData = new FormData();
                formData.append('editormd-image-file', file);
                var xhr = new XMLHttpRequest();
                xhr.onload = function () {
                    try {
                        var result = JSON.parse(this.responseText);
                        if(result.success == 1){
                            cm.replaceSelection("![](" + result.url + ")");
                        } 
                    } catch(err) {
                        console.log(err)
                    }
                };
                xhr.open('POST', '/image/upload', true);
                xhr.send(formData);
            });
```

**Comment by gentao123** [comment]
@ourforPP 加了代码，在编辑器还是不能直接粘贴图片哦。

**Comment by ourforPP** [comment]
可以的，我实验通过并且在用的，是不是加错地方了，或者看看控制台是否有报错

**Comment by gentao123** [comment]
@ourforPP 试了，火狐浏览器不行，edge可以。

**Comment by ourforPP** [comment]
@gentao123 日常用chrome，所以没测试其它浏览器，可能是浏览器事件不一样或者剪切板事件被关闭了，可以看下是否有相关开关

**Comment by shenxiaomei** [comment]
您好，我这边将代码粘贴进/static/plugin/editor.md/editormd.js 也是无效的，是有什么安全设置吗？

**Comment by shenxiaomei** [comment]
> 可以的，我实验通过并且在用的，是不是加错地方了，或者看看控制台是否有报错

老铁，我这边加了代码也不行。。。。也没看到报错，能请教下吗？

**Comment by ourforPP** [comment]
@shenxiaomei 过去一段时间了，有点忘了，719052021，加QQ聊吧

**Comment by yuchuan820** [comment]
添加后不生效也不报错
![image](https://user-images.githubusercontent.com/12994898/79094010-a6760c80-7d88-11ea-96fa-e0eba00968da.png)

**Comment by ourforPP** [comment]
> 添加后不生效也不报错
> ![image](https://user-images.githubusercontent.com/12994898/79094010-a6760c80-7d88-11ea-96fa-e0eba00968da.png)
我印象中作者后续的版本中好像改了上传图片的后台接口吧，你自己抓一下接口，结果解析换一下，我现在还是旧版本，不太好验证

**Comment by ourforPP** [comment]
@yuchuan820 对了，这个只支持剪切板图片的粘贴，比如截图工具这种复制到剪切板的，不支持复制图片文件再粘贴

**Comment by yuchuan820** [comment]
> @yuchuan820 对了，这个只支持剪切板图片的粘贴，比如截图工具这种复制到剪切板的，不支持复制图片文件再粘贴

@ourforPP 魔改了下
![image](https://user-images.githubusercontent.com/12994898/79110458-07afd700-7dad-11ea-9c66-e1c773facf5f.png)

**Comment by phachon** [comment]
建议是新写一个 js 文件实现，不要修改 /plugin/editor.md/editormd.js 插件里的。这样不好升级。

**Comment by luozantu** [comment]
图片上传接口新增了document_id，需要修改一下代码：
            //监听剪切板事件
            var cm = this.cm;
            this.codeMirror[0].addEventListener("paste", function (e) {
                if ( !(e.clipboardData && e.clipboardData.items) ) {
                    return;
                }
                var items = (event.clipboardData && event.clipboardData.items) || [];
                var file = null;
                if (items && items.length) {
                    for (var i = 0; i < items.length; i++) {
                        if (items[i].type.indexOf('image') !== -1) {
                            file = items[i].getAsFile();
                            break;
                        }
                    }
                }
                var reader = new FileReader();
                reader.readAsDataURL(file);
                var formData = new FormData();
                formData.append('editormd-image-file', file);
                var xhr = new XMLHttpRequest();
                xhr.onload = function () {
                    try {
                        var result = JSON.parse(this.responseText);
                        if(result.success == 1){
                            cm.replaceSelection("![](" + result.url + ")");
                        } 
                    } catch(err) {
                        console.log(err)
                    }
                };
                let document_id;
                let query = window.location.search.substring(1);
                let vars = query.split("&");
                for (var i=0;i<vars.length;i++) {
                   var pair = vars[i].split("=");
                   if(pair[0] == 'document_id'){
                    document_id = pair[1];
                   }
                }
                xhr.open('POST', '/image/upload?document_id='+ document_id, true);
                xhr.send(formData);
            });

**Comment by luozantu** [comment]
这样改还有个问题，就是只能粘贴一次图片，这个问题其实是后端设计不合理引起的，后端居然是用文件名排重的，也就是说同样文件名的图片，整个系统只能上传一次，可以修改下后端的逻辑，我懒得重新打包了，js给图片加个时间戳的名字就算了，代码如下:
 //监听剪切板事件
            var cm = this.cm;
            this.codeMirror[0].addEventListener("paste", function (e) {
                if ( !(e.clipboardData && e.clipboardData.items) ) {
                    return;
                }
                var items = (event.clipboardData && event.clipboardData.items) || [];
                var file = null;
                if (items && items.length) {
                    for (var i = 0; i < items.length; i++) {
                        if (items[i].type.indexOf('image') !== -1) {
                            file = items[i].getAsFile();
                            break;
                        }
                    }
                }
                var reader = new FileReader();
                reader.readAsDataURL(file);
		let random = Date.parse(new Date());
		let newFile = new File([file],random,{type:file.type});
                var formData = new FormData();
                formData.append('editormd-image-file', newFile);
                var xhr = new XMLHttpRequest();
                xhr.onload = function () {
                    try {
                        var result = JSON.parse(this.responseText);
                        if(result.success == 1){
                            cm.replaceSelection("![](" + result.url + ")");
                        } 
                    } catch(err) {
                        console.log(err)
                    }
                };
                let document_id;
                let query = window.location.search.substring(1);
                let vars = query.split("&");
                for (var i=0;i<vars.length;i++) {
                   var pair = vars[i].split("=");
                   if(pair[0] == 'document_id'){
                    document_id = pair[1];
                   }
                }
                xhr.open('POST', '/image/upload?document_id='+ document_id + '&guid='+ random, true);
                xhr.send(formData);
            });

**Comment by ourfor-pp** [comment]
@luozantu 适配新版的方案已经更新过了https://github.com/phachon/mm-wiki/issues/189#issue-618665256

你看到的这个是以前图片上传接口没改过时候的方案了
