### ISSUE TITLE
超级管理员不能屏蔽其他管理员

### ISSUE THREAD

**Issue by GrandMarch** [phachon/mm-wiki#73]
我测试 #68 时发现了点小问题。

1. 管理员不能删除账户，只能屏蔽。屏蔽后在数据库中查询用户的is_forbidden字段是1
2. 管理员不能屏蔽其他的管理员账户。

是在“用户管理”页面中给予管理员直接删除账户的权利好还是像现在这样管理员需要去数据库中删除？
管理员应该可以管理其他的管理员，就像windows账户一样，管理员是可以删除其他的管理员的，当然如果系统中只有一个管理员，那么肯定不允许删除唯一的管理员。

**Comment by phachon** [comment]
@GrandMarch 管理员权限的问题我在最新的版本应该已经修复了。#55
