### ISSUE TITLE
editor.md的bug比较多是不是可以考虑换一个markdown编辑器

### ISSUE THREAD

**Issue by GrandMarch** [phachon/mm-wiki#75]
editor.md的bug有点多，有些可能是editor.md自己的bug，有些bug可能来自有editor.md依赖的CodeMirror。
使用过程中我遇到的bug如下：

1.  https://github.com/pandao/editor.md/issues/689
2. https://github.com/pandao/editor.md/issues/241  
3. https://github.com/pandao/editor.md/issues/683
4. mardown 的引用  “”>” 有时候可能导致 “”>” 之后的内容不再解析，文本也不能保存了。
第二个bug是CodeMirror的锅，CodeMirror的开发者已经注意到这个问题有四年了，但是一直没有修正。

**Comment by phachon** [comment]
@GrandMarch 如果有更好的支持 markdown 的富文本插件可以提供一下
