### ISSUE TITLE
邮件测试发送报找不到文件，源码中拼接时候少输入了“/”

### ISSUE THREAD

**Issue by catlovegold** [phachon/mm-wiki#76]
mm-wiki/app/modules/system/controllers/email.go

328行  emailTemplate := beego.BConfig.WebConfig.ViewsPath + "system/email/template_test.html"

beego.BConfig.WebConfig.ViewsPath + "/system/email/template_test.html"

mm-wiki/app/controllers/page.go
533 行 也是

发送更新通知时，也有这个问题

**Comment by phachon** [comment]
@catlovegold 已修复，下一版本更新

**Comment by phachon** [comment]
v0.1.4 fix
