### ISSUE TITLE
希望权限部分更细点。

### ISSUE THREAD

**Issue by jijianming** [phachon/mm-wiki#86]
目前只能在空间级别做权限，希望可以增加对空间下面文档和目录的权限。

**Comment by jijianming** [comment]
![image](https://user-images.githubusercontent.com/15081733/61110976-0e768a00-a4bb-11e9-951a-fa1431121d98.png)
比如，游戏项目大家都有所有权限，对于不同目录不同人有不同权限。

**Comment by phachon** [comment]
@jijianming 可以建多个空间来区分

**Comment by jijianming** [comment]
ok
