### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by DonaldTsang** [phachon/mm-wiki#88]
I would like to know more about a Go+MD based wiki but I am not that good in Chinese,
is it possible to write a ReadME that is English for the wider public to see?

Also regarding the features:
1. Does this Wiki have branching/forking for mirrors?
2. Does this Wiki have user permissions and management?
3. Does this Wiki have cross-links for pages to link without URL?
4. Does this Wiki have forum/chats for page discussion?
5. Does this Wiki have page versioning?
6. Does this Wiki have page categorization?

**Comment by ruoranw** [comment]
Hi, I can help with the English version Readme. Do you accept PR?

**Comment by phachon** [comment]
@ruoranw 

Welcome to add English version Readme.

But Sorry, Wiki system text does not support English.

**Comment by ruoranw** [comment]
Ok, I'll get started soon.

**Comment by DonaldTsang** [comment]
@ruoranw @phachon any ideas on the 6 bullet points?

**Comment by phachon** [comment]
@DonaldTsang  Please read english version Readme.
