### ISSUE TITLE
报这个

### ISSUE THREAD

**Issue by zhouheng001** [phachon/mm-wiki#94]
package mm-wiki/app/...: unrecognized import path "mm-wiki/app/..." (import path does not begin with hostname)

**Comment by phachon** [comment]
@zhouheng001g GOPATH 没设置对吧

**Comment by zhouheng001** [comment]
> 
> 
> @zhouheng001g GOPATH 没设置对吧

其它包都能正常下载,只有这个wiki/app...这个包下载不下来
